import {
  faAlignCenter,
  faAlignLeft,
  faAlignRight,
  faArrowDown,
  faArrowRightArrowLeft,
  faArrowRotateForward,
  faArrowUp,
  faCheck,
  faChevronRight,
  faCircle,
  faCircleCheck,
  faClock,
  faDumbbell,
  faFile,
  faFlag,
  faFloppyDisk,
  faHeart,
  faHome,
  faPen,
  faPlus,
  faShare,
  faTrash,
  faX,
} from '@fortawesome/free-solid-svg-icons';

export const icons = {
  dumbbell: faDumbbell,
  floppy: faFloppyDisk,
  chevronRight: faChevronRight,
  flag: faFlag,
  circle: faCircle,
  circleChecked: faCircleCheck,
  down: faArrowDown,
  up: faArrowUp,
  trash: faTrash,
  x: faX,
  pen: faPen,
  check: faCheck,
  plus: faPlus,
  arrowRightArrowLeft: faArrowRightArrowLeft,
  clock: faClock,
  file: faFile,
  arrRotate: faArrowRotateForward,
  heart: faHeart,
  share: faShare,
  home: faHome,
  alRight: faAlignRight,
  alLeft: faAlignLeft,
  alCenter : faAlignCenter
};
